#!/usr/bin/env ruby

#
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.
#

UPPER_BOUND = (ARGV[0] || 4_000_000).to_i

prev_term, curr_term = 1, 2

sum = 0
while curr_term < UPPER_BOUND do
  sum += curr_term if curr_term % 2 == 0
  prev_term, curr_term = curr_term, prev_term + curr_term
end
puts sum
